import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Button from "@/components/Button";
import CoffeeCard from "@/components/CoffeeCard";

const coffees = [
  { name: "Cappuccino", description: "Rich espresso with a silky cloud of milk foam.", price: "Rp 28.000", image: "https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&w=900&q=85" },
  { name: "Café Latte", description: "A comforting balance of espresso and steamed milk.", price: "Rp 30.000", image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=900&q=85" },
  { name: "Americano", description: "Clean, bold espresso with a lingering roasted finish.", price: "Rp 25.000", image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=900&q=85" },
];

export default function Home() {
  return <div className="page-shell">
    <section id="home" className="relative min-h-[760px] bg-ink text-cream lg:min-h-screen"><Navbar /><div className="mx-auto grid min-h-[760px] max-w-360 items-center gap-12 px-6 pt-30 pb-14 lg:min-h-screen lg:grid-cols-[.92fr_1.08fr] lg:gap-20 lg:px-12 lg:pt-24">
      <div className="reveal relative z-10 pt-12 lg:pt-0"><p className="eyebrow mb-7">Coffee & Roastery · Est. 2020</p><h1 className="font-display text-5xl leading-[1.03] sm:text-6xl lg:text-8xl">Crafted Coffee,<br /><em className="font-normal text-gold">Warm Moments.</em></h1><p className="mt-7 max-w-md text-base leading-7 text-cream/65">Carefully crafted coffee for every moment of your day. A slow, thoughtful pause in the heart of the city.</p><div className="mt-9 flex flex-wrap gap-3"><Button href="#menu">Explore Menu</Button><Button href="#visit" variant="outline">Visit Us</Button></div></div>
      <div className="reveal-delay relative mx-auto w-full max-w-2xl lg:ml-auto"><div className="absolute -left-4 -top-4 h-20 w-20 border-l border-t border-gold lg:-left-8 lg:-top-8" /><div className="photo-wash h-[430px] sm:h-[540px] lg:h-[min(70vh,680px)]"><img src="https://images.unsplash.com/photo-1512568400610-62da28bc8a13?auto=format&fit=crop&w=1400&q=90" alt="Fresh coffee with latte art" className="h-full w-full object-cover" /></div><p className="mt-4 text-right text-[10px] font-bold tracking-[.16em] text-cream/50 uppercase">Slow mornings / Good coffee</p></div>
    </div></section>
    <section className="mx-auto grid max-w-360 gap-12 px-6 py-22 lg:grid-cols-2 lg:items-center lg:gap-28 lg:px-12 lg:py-32"><div className="relative"><div className="h-[430px] overflow-hidden sm:h-[540px]"><img src="https://images.unsplash.com/photo-1445116572660-236099ec97a0?auto=format&fit=crop&w=1200&q=85" alt="Warm coffee shop interior" className="h-full w-full object-cover" /></div><div className="absolute -bottom-7 -right-2 bg-coffee px-7 py-6 text-cream sm:-right-7"><p className="font-display text-3xl text-gold">06+</p><p className="mt-1 text-xs tracking-widest uppercase">Years brewing</p></div></div><div><p className="eyebrow mb-6 text-coffee">Our story</p><h2 className="font-display text-4xl leading-tight text-ink sm:text-5xl">More Than<br /><em className="font-normal text-coffee">Just Coffee</em></h2><p className="mt-7 max-w-lg leading-7 text-ink/65">We bring together quality beans, thoughtful craft, and a space that feels like yours. Every cup is made with care for its taste, aroma, and the moment it creates.</p><a href="/services" className="mt-8 inline-flex border-b border-gold pb-2 text-xs font-bold tracking-[.14em] uppercase transition hover:text-coffee">Discover our story <span className="ml-4 text-gold">→</span></a></div></section>
    <section id="menu" className="bg-ink px-6 py-22 text-cream lg:px-12 lg:py-30"><div className="mx-auto max-w-360"><div className="mb-12 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="eyebrow mb-5">A little something</p><h2 className="font-display text-4xl sm:text-5xl">Made for your<br /><em className="font-normal text-gold">everyday ritual.</em></h2></div><p className="max-w-xs text-sm leading-6 text-cream/55">Simple ingredients, carefully crafted and served exactly how you like it.</p></div><div className="grid gap-6 md:grid-cols-3">{coffees.map((coffee, index) => <CoffeeCard key={coffee.name} coffee={coffee} featured={index === 0} />)}</div><div className="mt-10 text-center"><Button href="/menu" variant="outline">View Full Menu</Button></div></div></section>
    <section id="visit" className="bg-coffee px-6 py-22 text-center text-cream lg:py-30"><div className="mx-auto max-w-2xl"><p className="eyebrow mb-6 justify-center">Your table awaits</p><h2 className="font-display text-4xl leading-tight sm:text-6xl">Your Next Favorite Cup<br /><em className="font-normal text-gold">Is Waiting.</em></h2><p className="mx-auto mt-6 max-w-xl leading-7 text-cream/65">Visit our coffee shop and enjoy your favorite brew in a warm, comfortable space made for unhurried moments.</p><Button href="/contact" className="mt-9">Visit Us</Button></div></section>
    <Footer />
  </div>;
}
